### ISSUE TITLE
About the codes

### ISSUE THREAD

**Issue by WenxSong** [yingtaoluo/Highly-Nonlinear-PDE-Discovery#1]
Thanks for sharing your nice work and codes. I have some questions about the codes. Why is there a PINN module in the codes? Is the kernel estimation used for equation structure discovery while the field is reconstructed by PINNs? Moreover, I tried to run the codes, but they just stopped in the first training step (epoch 1). Could you please help me with these questions? Thanks a lot!

**Comment by yingtaoluo** [comment]
Thank you for your interest! The PINN module is the knowledge constraint part of the model, which is explained in Sec 4.2. PINN is one possible way to implement it. The kernel is the other part of the model. 

For the code running, could you show the error? It will help me understand what problems you run into. I will post the requirement soon and please make sure the packages are installed correctly.

**Comment by WenxSong** [comment]
Thanks for your quick response. I just found it is due to the slow training processes, not a bug. As far as I am concerned, the training processes are three steps: first, training a neural network to estimate the dervatitives; second, using the proposed kernel-based sparse regression to discover the PDE; and third, fine-tuning the coefficent field. I'm not sure if I'm understanding this correctly.

**Comment by yingtaoluo** [comment]
You are correct. If there is enough GPU memory, try setting GPU arg to >=0 would be helpful.

**Comment by WenxSong** [comment]
Thanks for your help!
